Repository DIT113-V22/group-14, pull requests merged in 2022-05, with the labels that each got.

#54 Database backend
  android/SmartcarMqttController/app/build.gradle
  android/SmartcarMqttController/app/google-services.json
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/Firebase.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/HomeScreen.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/MainActivity.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/Plants.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/StatusScreen.java
  android/SmartcarMqttController/build.gradle
Labels: sprint #2, High Priority, User Story

#56 Added control of speed (faster or slower)
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/MainActivity.java
  android/SmartcarMqttController/app/src/main/res/layout/activity_main.xml
Labels: sprint #2, User Story

#57 Fixed obstacle detection and added tank mode
  .github/workflows/arduino-build.yml
  android/SmartcarMqttController/app/local.properties
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/MainActivity.java
  arduino/smartcar/smartcar.ino
  arduino/smartcar_mqtt/smartcar_mqtt.ino
Labels: sprint #2

#64 speed control
  android/SmartcarMqttController/app/local.properties
  android/SmartcarMqttController/app/src/main/AndroidManifest.xml
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/MainActivity.java
  android/SmartcarMqttController/app/src/main/res/drawable/button_focused.xml
  android/SmartcarMqttController/app/src/main/res/drawable/button_normal.xml
  android/SmartcarMqttController/app/src/main/res/drawable/button_select_states.xml
  android/SmartcarMqttController/app/src/main/res/drawable/button_selected.xml
  android/SmartcarMqttController/app/src/main/res/drawable/rabbit.png
  android/SmartcarMqttController/app/src/main/res/drawable/rabbit_button.xml
  android/SmartcarMqttController/app/src/main/res/drawable/turtle.webp
  android/SmartcarMqttController/app/src/main/res/drawable/turtle2.png
  android/SmartcarMqttController/app/src/main/res/layout/activity_main.xml
  android/SmartcarMqttController/app/src/main/res/values-night/themes.xml
  android/SmartcarMqttController/app/src/main/res/values/themes.xml
Labels: sprint #2, High Priority

#76 Color rendering fix
  android/SmartcarMqttController/app/build.gradle
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/HomeScreen.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/MainActivity.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/QrCodeTest.java
Labels: sprint #2

#80 CI fix
  android/SmartcarMqttController/build.gradle
  local.properties
Labels: bug, High Priority

#81 Login screen implementation
  android/SmartcarMqttController/app/build.gradle
  android/SmartcarMqttController/app/src/main/AndroidManifest.xml
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/HomeScreen.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/LoginScreen.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/MainActivity.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/Pop.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/QrCodeTest.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/StatusScreen.java
  android/SmartcarMqttController/app/src/main/res/drawable/ic_baseline_visibility_24.xml
  android/SmartcarMqttController/app/src/main/res/drawable/ic_baseline_visibility_off_24.xml
  android/SmartcarMqttController/app/src/main/res/ic_launcher-web.png
  android/SmartcarMqttController/app/src/main/res/layout-land/activity_main.xml
  android/SmartcarMqttController/app/src/main/res/layout/activity_login_screen.xml
  android/SmartcarMqttController/app/src/main/res/layout/popwindow.xml
  android/SmartcarMqttController/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/SmartcarMqttController/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/SmartcarMqttController/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/SmartcarMqttController/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/SmartcarMqttController/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/SmartcarMqttController/app/src/main/res/mipmap-ldpi/ic_launcher.png
  android/SmartcarMqttController/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/SmartcarMqttController/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/SmartcarMqttController/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/SmartcarMqttController/app/src/main/res/playstore-icon.png
  android/SmartcarMqttController/app/src/main/res/values/colors.xml
  android/SmartcarMqttController/app/src/main/res/values/ic_launcher_background.xml
  android/SmartcarMqttController/app/src/main/res/values/strings.xml
  android/SmartcarMqttController/app/src/main/res/values/themes.xml
Labels: sprint #3, Medium Priority

#86 74 stop driving when releasing button
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/MainActivity.java
  android/SmartcarMqttController/app/src/main/res/layout-land/activity_main.xml
  android/SmartcarMqttController/app/src/main/res/layout/activity_main.xml
Labels: sprint #3, User Story

#92 Status screen info queried from db
  .gitignore
  android/PlantholderApplication/app/build.gradle
  android/PlantholderApplication/app/google-services.json
  android/PlantholderApplication/app/src/androidTest/java/ExampleInstrumentedTest.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/Firebase.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/StatusScreen.java
  android/PlantholderApplication/app/src/main/res/layout-land/activity_status_screen.xml
  android/PlantholderApplication/app/src/main/res/values/strings.xml
Labels: sprint #3

#93 Application Add new plant screen and layout
  android/PlantholderApplication/app/src/main/java/plantholder/application/AddPlantScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/Firebase.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/HomeScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/Plants.java
  android/PlantholderApplication/app/src/main/res/drawable/engine.png
  android/PlantholderApplication/app/src/main/res/drawable/growth.png
  android/PlantholderApplication/app/src/main/res/layout-land/activity_home_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/add_plant_screen.xml
  android/PlantholderApplication/app/src/main/res/values/strings.xml
Labels: sprint #3, User Story

#96 Fix bug when creating new plants
  android/PlantholderApplication/app/src/main/java/plantholder/application/Plants.java
Labels: bug, High Priority

#97 Application login page and user credential
  android/PlantholderApplication/app/src/main/AndroidManifest.xml
  android/PlantholderApplication/app/src/main/java/plantholder/application/CreateAccount.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/Firebase.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/ForgotPassword.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/LoginScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/MainActivity.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/Pop.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/StatusScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/User.java
  android/PlantholderApplication/app/src/main/res/drawable/close_icon.xml
  android/PlantholderApplication/app/src/main/res/drawable/lock.xml
  android/PlantholderApplication/app/src/main/res/drawable/user_icon.png
  android/PlantholderApplication/app/src/main/res/drawable/userimage.xml
  android/PlantholderApplication/app/src/main/res/layout/activity_login_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/forgot_password_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/new_user_window.xml
Labels: sprint #3, User Story

#100 improvements to status screen
  android/PlantholderApplication/app/src/main/AndroidManifest.xml
  android/PlantholderApplication/app/src/main/java/plantholder/application/AddPlantScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/Firebase.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/StatusScreen.java
  android/PlantholderApplication/app/src/main/res/layout-land/activity_status_screen.xml
Labels: sprint #3

#102 Navigation buttons on application changed
  android/PlantholderApplication/app/src/main/java/plantholder/application/MainActivity.java
  android/PlantholderApplication/app/src/main/res/drawable-v24/down_arrow.webp
  android/PlantholderApplication/app/src/main/res/drawable-v24/left_arrow.png
  android/PlantholderApplication/app/src/main/res/drawable-v24/right_arrow.webp
  android/PlantholderApplication/app/src/main/res/drawable-v24/up_arrow.webp
  android/PlantholderApplication/app/src/main/res/drawable/auto.xml
  android/PlantholderApplication/app/src/main/res/drawable/auto_pilot.xml
  android/PlantholderApplication/app/src/main/res/drawable/autopilot_button.xml
  android/PlantholderApplication/app/src/main/res/layout-land/activity_main.xml
  android/SmartcarMqttController/gradle/wrapper/gradle-wrapper.jar
  android/SmartcarMqttController/gradle/wrapper/gradle-wrapper.properties
  android/SmartcarMqttController/gradlew
  android/SmartcarMqttController/gradlew.bat
Labels: sprint #3, User Story

#107 Update the UI layout
  android/PlantholderApplication/app/src/main/java/plantholder/application/AddPlantScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/LoginScreen.java
  android/PlantholderApplication/app/src/main/res/layout-land/activity_home_screen.xml
  android/PlantholderApplication/app/src/main/res/layout-land/activity_main.xml
  android/PlantholderApplication/app/src/main/res/layout-land/activity_status_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/activity_login_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/add_plant_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/new_user_window.xml
  android/PlantholderApplication/app/src/main/res/values/colors.xml
Labels: sprint #3, improvements

#112 Add Information and Statistics screen
  android/PlantholderApplication/app/build.gradle
  android/PlantholderApplication/app/src/main/AndroidManifest.xml
  android/PlantholderApplication/app/src/main/java/plantholder/application/HomeScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/InformationScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/MainActivity.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/PlantStatistics.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/Plants.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/PlantsAdapter.java
  android/PlantholderApplication/app/src/main/res/drawable/chart.png
  android/PlantholderApplication/app/src/main/res/layout-land/activity_home_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/activity_home_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/activity_information_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/activity_main.xml
  android/PlantholderApplication/app/src/main/res/layout/activity_plant_statistics.xml
  android/PlantholderApplication/app/src/main/res/layout/activity_status_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/show_plants.xml
Labels: sprint #3

#115 Pie chart to display plant health statistics
  .DS_Store
  android/.DS_Store
  android/PlantholderApplication/app/build.gradle
  android/PlantholderApplication/app/src/main/java/plantholder/application/PlantStatistics.java
  android/PlantholderApplication/app/src/main/res/layout/activity_plant_statistics.xml
  android/SmartcarMqttController/.DS_Store
  android/SmartcarMqttController/gradle/.DS_Store
Labels: improvements

#116 Qr code processing
  android/PlantholderApplication/app/build.gradle
  android/PlantholderApplication/app/src/main/AndroidManifest.xml
  android/PlantholderApplication/app/src/main/java/plantholder/application/MainActivity.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/QrCodeProcessing.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/StatusScreen.java
  android/PlantholderApplication/app/src/main/res/layout-land/activity_status_screen.xml
  android/SmartcarMqttController/gradle/wrapper/gradle-wrapper.jar
  android/SmartcarMqttController/gradle/wrapper/gradle-wrapper.properties
  android/SmartcarMqttController/gradlew
  android/SmartcarMqttController/gradlew.bat
Labels: sprint #3

#118 105 highlighting buttons
  android/PlantholderApplication/app/src/main/java/plantholder/application/LoginScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/MainActivity.java
  android/PlantholderApplication/app/src/main/res/drawable-v24/down_arrow.webp
  android/PlantholderApplication/app/src/main/res/drawable-v24/left_arrow.png
  android/PlantholderApplication/app/src/main/res/drawable-v24/right_arrow.webp
  android/PlantholderApplication/app/src/main/res/drawable-v24/up_arrow.webp
  android/PlantholderApplication/app/src/main/res/drawable/auto_pilot.xml
  android/PlantholderApplication/app/src/main/res/drawable/autopilot_button.xml
  android/PlantholderApplication/app/src/main/res/drawable/background_down.xml
  android/PlantholderApplication/app/src/main/res/drawable/background_left.xml
  android/PlantholderApplication/app/src/main/res/drawable/background_right.xml
  android/PlantholderApplication/app/src/main/res/drawable/background_up.xml
  android/PlantholderApplication/app/src/main/res/drawable/button_focused.xml
  android/PlantholderApplication/app/src/main/res/drawable/button_selected.xml
  android/PlantholderApplication/app/src/main/res/drawable/down.png
  android/PlantholderApplication/app/src/main/res/drawable/down_arrow_background.xml
  android/PlantholderApplication/app/src/main/res/drawable/down_green.png
  android/PlantholderApplication/app/src/main/res/drawable/left.png
  android/PlantholderApplication/app/src/main/res/drawable/left_arrow_background.xml
  android/PlantholderApplication/app/src/main/res/drawable/left_green.png
  android/PlantholderApplication/app/src/main/res/drawable/right.png
  android/PlantholderApplication/app/src/main/res/drawable/right_arrow_background.xml
  android/PlantholderApplication/app/src/main/res/drawable/right_green.png
  android/PlantholderApplication/app/src/main/res/drawable/up.png
  android/PlantholderApplication/app/src/main/res/drawable/up_arrow_background.xml
  android/PlantholderApplication/app/src/main/res/drawable/up_green.png
  android/PlantholderApplication/app/src/main/res/layout-land/activity_main.xml
  android/PlantholderApplication/app/src/main/res/layout/activity_login_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/activity_main.xml
  android/SmartcarMqttController/.DS_Store
  android/SmartcarMqttController/gradle/.DS_Store
Labels: sprint #4, User Story

#121 Go back to previous screen
  android/PlantholderApplication/app/src/main/java/plantholder/application/AddPlantScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/CreateAccount.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/ForgotPassword.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/HomeScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/InformationScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/MainActivity.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/PlantStatistics.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/StatusScreen.java
Labels: bug, sprint #4, High Priority, improvements

#127 Made statistics screen compatible with smaller devices
  android/.DS_Store
  android/PlantholderApplication/app/src/main/java/plantholder/application/PlantStatistics.java
  android/PlantholderApplication/app/src/main/res/layout/activity_plant_statistics.xml
Labels: improvements

#129 Obstacle detection update
  arduino/smartcar/smartcar.ino
Labels: bug

#130 Improvements to login screen features
  android/PlantholderApplication/app/src/main/java/plantholder/application/CreateAccount.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/ForgotPassword.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/LoginScreen.java
  android/PlantholderApplication/app/src/main/res/drawable/button_focused.xml
  android/PlantholderApplication/app/src/main/res/drawable/button_selected.xml
  android/PlantholderApplication/app/src/main/res/values/colors.xml
Labels: sprint #4, improvements

#134 Add extra functions to the Auto pilot button
  android/PlantholderApplication/app/src/main/java/plantholder/application/InformationScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/MainActivity.java
Labels: sprint #4, User Story

#140 Arduino code cleanup
  arduino/smartcar/smartcar.ino
Labels: sprint #4, improvements

#142 71 code improvements android studio
  android/PlantholderApplication/app/src/main/AndroidManifest.xml
  android/PlantholderApplication/app/src/main/java/plantholder/application/AddPlantScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/CreateAccount.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/Firebase.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/ForgotPassword.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/HomeScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/InformationScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/LoginScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/MainActivity.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/MqttClient.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/PlantStatistics.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/Plants.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/PlantsAdapter.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/Pop.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/QrCodeProcessing.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/StatusScreen.java
  android/PlantholderApplication/app/src/main/java/plantholder/application/User.java
  android/PlantholderApplication/app/src/main/res/drawable/auto.xml
  android/PlantholderApplication/app/src/main/res/drawable/background_down.xml
  android/PlantholderApplication/app/src/main/res/drawable/background_left.xml
  android/PlantholderApplication/app/src/main/res/drawable/background_right.xml
  android/PlantholderApplication/app/src/main/res/drawable/background_up.xml
  android/PlantholderApplication/app/src/main/res/drawable/previous.png
  android/PlantholderApplication/app/src/main/res/drawable/turtle.webp
  android/PlantholderApplication/app/src/main/res/layout-land/activity_home_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/activity_home_screen.xml
Labels: sprint #3, sprint #4, improvements

#143 update readme file
  README.md
Labels: documentation, sprint #4

#145 Update README.md
  README.md
Labels: improvements

#148 Update layout of two screens and updates app name
  android/PlantholderApplication/app/src/main/java/plantholder/application/User.java
  android/PlantholderApplication/app/src/main/res/layout/add_plant_screen.xml
  android/PlantholderApplication/app/src/main/res/layout/forgot_password_screen.xml
  android/PlantholderApplication/app/src/main/res/values/strings.xml
Labels: High Priority, improvements

#150 update ReadMe with video
  README.md
Labels: documentation, sprint #4, User Story, Assignments
