Repository DIT113-V22/group-14, pull requests merged in 2022-04, with the labels that each got.

#29 Basic car control
  arduino/smartcar/smartcar.ino
Labels: sprint #1, High Priority, User Story

#30 Basic obstacle avoidance
  arduino/smartcar/smartcar.ino
Labels: sprint #1, High Priority, Assignments

#44 Main menu plant application UI
  .DS_Store
  android/.DS_Store
  android/SmartcarMqttController/app/build.gradle
  android/SmartcarMqttController/app/src/main/AndroidManifest.xml
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/HomeScreen.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/MainActivity.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/StatusScreen.java
  android/SmartcarMqttController/app/src/main/res/drawable/field.png
  android/SmartcarMqttController/app/src/main/res/drawable/previous.png
  android/SmartcarMqttController/app/src/main/res/drawable/tomato.JPG
  android/SmartcarMqttController/app/src/main/res/layout/activity_home_screen.xml
  android/SmartcarMqttController/app/src/main/res/layout/activity_main.xml
  android/SmartcarMqttController/app/src/main/res/layout/activity_status_screen.xml
Labels: sprint #1, High Priority

#46 Basic Android app
  .DS_Store
  .github/workflows/android-ci.yml
  .gitignore
  android/.DS_Store
  android/SmartcarMqttController/app/.gitignore
  android/SmartcarMqttController/app/build.gradle
  android/SmartcarMqttController/app/proguard-rules.pro
  android/SmartcarMqttController/app/src/androidTest/java/platis/solutions/smartcarmqttcontroller/ExampleInstrumentedTest.java
  android/SmartcarMqttController/app/src/main/AndroidManifest.xml
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/HomeScreen.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/MainActivity.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/MqttClient.java
  android/SmartcarMqttController/app/src/main/java/platis/solutions/smartcarmqttcontroller/StatusScreen.java
  android/SmartcarMqttController/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/SmartcarMqttController/app/src/main/res/drawable/field.png
  android/SmartcarMqttController/app/src/main/res/drawable/ic_launcher_background.xml
  android/SmartcarMqttController/app/src/main/res/drawable/logo.png
  android/SmartcarMqttController/app/src/main/res/drawable/plinder_4.png
  android/SmartcarMqttController/app/src/main/res/drawable/previous.png
  android/SmartcarMqttController/app/src/main/res/drawable/tomato.JPG
  android/SmartcarMqttController/app/src/main/res/layout/activity_home_screen.xml
  android/SmartcarMqttController/app/src/main/res/layout/activity_main.xml
  android/SmartcarMqttController/app/src/main/res/layout/activity_status_screen.xml
  android/SmartcarMqttController/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/SmartcarMqttController/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/SmartcarMqttController/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/SmartcarMqttController/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/SmartcarMqttController/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/SmartcarMqttController/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/SmartcarMqttController/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/SmartcarMqttController/app/src/main/res/values-night/themes.xml
  android/SmartcarMqttController/app/src/main/res/values/colors.xml
  android/SmartcarMqttController/app/src/main/res/values/strings.xml
  android/SmartcarMqttController/app/src/main/res/values/themes.xml
  android/SmartcarMqttController/app/src/test/java/platis/solutions/smartcarmqttcontroller/ExampleUnitTest.java
  android/SmartcarMqttController/build.gradle
  android/SmartcarMqttController/gradle.properties
  android/SmartcarMqttController/gradle/wrapper/gradle-wrapper.jar
  android/SmartcarMqttController/gradle/wrapper/gradle-wrapper.properties
  android/SmartcarMqttController/gradlew
  android/SmartcarMqttController/gradlew.bat
  android/SmartcarMqttController/settings.gradle
  arduino/smartcar_mqtt/smartcar_mqtt.ino
Labels: sprint #1, High Priority

#47 Update README.md
  README.md
Labels: documentation
